swagger: '2.0'
info:
  version: "1.1"
  title: 'JHProject ML API'
  description: 'Machine learning API for 2017 JH Project.'
  
schemes:
 - http
 
securityDefinitions:
  Bearer:
    type: apiKey 
    name: Authorization
    in: header

security:
  - Bearer: []

paths:
  /models:
    post:
      tags:
        - model
      summary: Start training a machine-learning model with the given model_id.
      operationId: createModel
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: data
          in: body
          description: data
          required: true
          schema:
            $ref: '#/definitions/CreateModelData'
      responses:
        201:
          description: Model successfully in training
          schema:
            $ref: '#/definitions/TrainingResponse'
        404:
          description: If any of the job_id, training_data, output_directory_path, input_columns, output_column or required parameters do not exist.
          schema:
            $ref: '#/definitions/404Error'
        401:
          description: If the user does not have authorisation to access the training data.
          schema:
            $ref: '#/definitions/Error'
        400:
          description: If a non existing parameter is given or if a parameter is given an incorrect value.
          schema:
            $ref: '#/definitions/Error'
  /models/{project_name}/{model_id}:      
    get:
      tags:
        - model
      summary: Get status of model training.
      operationId: status
      produces:
        - application/json
      parameters:
        - name: model_id
          in: path
          description: Model UUID
          required: true
          type: string
        - name: project_name
          in: path
          description: Name of project model is within
          required: true
          type: string
      responses:
        200:
          description: "Training status sent."
          schema:
            $ref: '#/definitions/Status'
        404:
          description: "If model_id does not exist."
          schema:
            $ref: '#/definitions/404Error'
        401:
          description: "If user does not have permission to view the project the model is in."
          schema:
            $ref: '#/definitions/Error'
    delete:
      tags:
        - model
      summary: Forcefully stop training a model. If model has finished training, it deletes the model file in BE.
      operationId: deleteTraining
      produces:
        - application/json
      parameters:
        - name: model_id
          in: path
          description: Model UUID
          required: true
          type: string
        - name: project_name
          in: path
          description: Name of project model is within
          required: true
          type: string
      responses:
        204:
          description: "Model deleted."
          schema:
            $ref: '#/definitions/Empty'
        404:
          description: "If model provided does not exist."
          schema:
            $ref: '#/definitions/404Error'
        401:
          description: "If user does not have permission to view the model."
          schema:
            $ref: '#/definitions/Error'
  /models/stop/{project_name}/{model_id}:
    delete:
      tags:
        - model
      summary: Forcefully stop training an incrementally trained model. The partially trained model will be saved and can be used for predictions.
      operationId: stopTraining
      produces:
        - application/json
      parameters:
      - name: model_id
        in: path
        description: Model UUID
        required: true
        type: string
      - name: project_name
        in: path
        description: Name of project model is within
        required: true
        type: string
      responses:
        204:
          description: "Model training successfully stopped, or had successfully finished before stop call was made."
          schema:
            $ref: '#/definitions/Empty'
        404:
          description: "If model provided does not exist."
          schema:
            $ref: '#/definitions/404Error'
        401:
          description: "If user does not have permission to view the model."
          schema:
            $ref: '#/definitions/Error'
        405:
          description: "If the model referenced is not partially-trainable."
          schema:
            $ref: '#/definitions/Error'
  /models/prediction/{project_name}/{model_id}:
    post:
      tags:
        - model
      summary: Get a prediction given a model and input data.
      operationId: getPrediction
      produces:
        - application/json
      parameters:
        - name: model_id
          in: path
          description: Model UUID
          required: true
          type: string
        - name: project_name
          in: path
          description: Name of project model is within
          required: true
          type: string
        - name: data
          in: body
          description: The input data for the model
          required: true
          schema:
            $ref: '#/definitions/PredictionInput'
      responses:
        200:
          description: "Prediction results were successfully calculated."
          schema:
            $ref: '#/definitions/GetPrediction'
        404:
          description: "If model or input_data does not exist."
          schema:
            $ref: '#/definitions/404Error'
  /models/{project_name}:
    get:
      tags:
        - model
      summary: Get a list of models inside a given project.
      operationId: getList
      parameters:
        - name: project_name
          in: path
          description: Project name
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: A list of models inside a project
          schema:
            $ref: '#/definitions/StatusArray'
        404:
          description: The project does not exist
          schema:
           $ref: '#/definitions/404Error'
        401:
          description: "If the user does not have permission to view the data file."
          schema:
            $ref: '#/definitions/Error'
          
  /suggest:
    post:
      tags:
        - algorithms
      summary: Suggest relevant ML algorithms for a given training set.
      operationId: suggest
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: data
          in: body
          description: data
          required: true
          schema:
            $ref: '#/definitions/RequestSuggestion'
      responses:
        200:
          description: "List of suggested algorithms found. The returned algorithms each have a score associated for ranking purposes, but implementations are not required to provide accurate scores - in this case, all scores should be the same."
          schema:
            $ref: '#/definitions/Suggest'
        404:
          description: "If any of input_columns, output_columns, or data_file provided do not exist."
          schema:
            $ref: '#/definitions/404Error'
        401:
          description: "If the user does not have permission to view the data file."
          schema:
            $ref: '#/definitions/Error'
  /jobs:
    get:
      tags:
        - algorithms
      summary: List all possible jobs ML supports.
      operationId: jobs
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: "List of all possible jobs the ML server can perform with a description of what type of data the job is performed on."
          schema:
            $ref: '#/definitions/Jobs'
            
definitions:
  Error:
    type: object
    properties:
      error:
        type: string
        description: An error code
      error_description:
        type: string
        description: A human readable description of the error
      user_message:
        type: string
        description: Optional message to display to user
  404Error:
    type: object
    properties:
      error:
        type: string
        description: An error code
      error_description:
        type: string
        description: A human readable description of the error
      user_message:
        type: string
        description: Optional message to display to user
      error_data:
        type: object
        properties:
          missing_fields:
            type: array
            items:
              type: string
              example: "input_data"
  DataInput:
    type: object
    properties:
      id:
        type: string
        description: File UUID
      project_name:
        type: string
        description: Name of the project the data file belongs to
  CreateModelData:
    type: object
    properties:
      refresh_token:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      job_id:
        type: string
        example: "nb83451"
      training_data:
        $ref: '#/definitions/DataInput'
      output_directory_path:
        type: string
        example: path/stuff/new_job
        description: Filepath to the directory where the user wants output files to be saved.
      input_columns:
        type: array
        items:
          $ref: '#/definitions/Column'
      output_columns:
        type: array
        items:
          $ref: '#/definitions/Column'
      parameters:
        type: object
        additionalProperties: true
        example:
          "k": 5
        description: An object of key value pairs where the key is the parameter id and the value is the parameter value. Parameters are as specified by the results of a /suggest or /jobs call.
  GetPrediction:
    type: object
    properties:
      data:
        $ref: '#/definitions/GetPredictionData'    
  GetPredictionData:
    type: object
    properties:
      result_type:
        $ref: '#/definitions/ParamType'
      results:
        type: array
        items:
          type: array
          items:
            type: string
            description: Data items - must be same data type as result_type but converted to string.
  PredictionInput:
    type: object
    properties:
      data_file:
        type: object
        properties:
          id:
            type: string
            description: File UUID
          project_name:
            type: string
            description: project name
      input_columns:
        type: array
        items:
          $ref: '#/definitions/Column'
  Status:
    type: object
    properties:
      data:
        $ref: '#/definitions/StatusData'
  StatusArray:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/StatusData'
  StatusData:
    type: object
    properties:
      percent_trained:
        minimum: 0
        maximum: 1
        type: number
        example: 0.3
      status:
        $ref: '#/definitions/JobStatusType'
      description:
        type: string
        description: Descriptive log of all that has occurred during the training of the model (accumulates over time).
      id:
        type: string
        description: Model ID
      start_time:
        type: string
        description: Time at which the model began training.
      started_by:
        type: string
        description: Username of the user who started the model training.
  RequestSuggestion:
    type: object
    properties:
      data_file:
        $ref: '#/definitions/DataInput'
      input_columns:
        type: array
        items:
          $ref: '#/definitions/Column'
      output_columns:
        type: array
        items:
          $ref: '#/definitions/Column'
  Suggest:
    type: object
    properties:
      data:
        $ref: '#/definitions/SuggestData'
  SuggestData:
    type: object
    properties:
      jobs:
        type: array
        items:
          type: object
          properties:
            job:
              $ref: '#/definitions/JobInfo'
            score:
              type: number
              minimum: 0
              maximum: 1
              example: 0.3
  Jobs:
    type: object
    properties:
      data:
        $ref: '#/definitions/JobsData'
  JobsData:
    type: object
    properties:
      jobs:
        type: array
        items:
          $ref: '#/definitions/JobInfo'
  JobInfo:
    type: object
    properties:
      job_id:
        type: string
        description: Unique ID of the ML job type, used to request the same job type again in a /training call.
        example: "83451"
      data_type: 
        type: string
        example: tabular
      algorithm_name:
        type: string
        example: Naive Bayes
      partial_training_support:
        type: boolean
      job_description:
        type: string
        example: Algorithm that calculates conditional probabilities, and then uses them to predict likely results.
        description: User friendly description of the job.
      parameters:
        type: array
        items:
          $ref: '#/definitions/Parameter'
  Parameter:
    type: object
    properties:
      id:
        type: string
        example: k
      required:
        type: boolean
        example: true
      type:
        $ref: '#/definitions/ParamType'
      description:
        type: string
        example: cross validation parameter
  Column:
    type: object
    properties:
      column_index:
        type: integer
        example: 4
      column_type:
        $ref: '#/definitions/DataType'
  DataType:
    type: string
    enum:
      - discrete
      - continuous
      - infer
      - imagefilepath
      - date
  ParamType:
    type: string
    enum:
      - integer
      - boolean
      - string
      - number
  JobStatusType:
    type: string
    description: State of training of an ML model
    enum:
      - running
      - complete
      - failed
      - cancelled
  Empty:
    type: object
    properties:
      data:
        type: object
  TrainingResponse:
    type: object
    properties:
      data:
        type: object
        properties:
          model_id:  
            type: string
        
# Added by API Auto Mocking Plugin
# Auto generated host and base urls. This is not permanent, and will likely need to change per group.
host: virtserver.swaggerhub.com
basePath: /JH-Project/machine-learning-api/1.0
